#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE DATABASE ${WIKIJS_DB_NAME};
    CREATE USER ${WIKIJS_DB_USER} WITH ENCRYPTED PASSWORD '${WIKIJS_DB_PASSWORD}';
    ALTER DATABASE ${WIKIJS_DB_NAME} OWNER TO ${WIKIJS_DB_USER};
    GRANT ALL PRIVILEGES ON DATABASE ${WIKIJS_DB_NAME} TO ${WIKIJS_DB_USER};
EOSQL
